default_config:

homeassistant:
  name: Bistro Tranquilo
  latitude: 52.359969
  longitude: 4.914359
  elevation: 24
  unit_system: metric
  currency: EUR
  time_zone: Europe/Amsterdam

# Add specific integrations (if needed)
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes

http:
  # Enables support for using a reverse proxy (e.g., Traefik)
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.68.251 # Replace with your Docker host's internal IP
    - 172.20.0.0/16 # Docker proxy network
