---

services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - "settings.env"
      - "secrets.env"
    image: ${REGISTRY:-bitwarden}/self-host:${TAG:-beta}
    restart: always
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden

  db:
    env_file:
      - "secrets.env"
    image: postgres:14
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  bitwarden:
  logs:
  data:
