---
title: "Homelab"
subtitle: "danielsteman.com"
logo: "assets/dark_circle.png"
header: true
footer: false

stylesheet:
  - "assets/catppuccin-mocha.css"

colorTheme: dark

services:
  - name: "Apps"
    icon: "fas fa-cloud"
    items:
      - name: "Home Assistant"
        subtitle: "Home automation"
        tag: "app"
        url: "https://homelab.danielsteman.com"
        target: "_blank"
      - name: "Mattermost"
        subtitle: "Chat"
        tag: "app"
        url: "https://chat.danielsteman.com"
        target: "_blank"
      - name: "Bitwarden"
        subtitle: "Password manager"
        tag: "app"
        url: "#"
        target: "_blank"

  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - name: "Traefik"
        subtitle: "Reverse proxy dashboard"
        tag: "infra"
        url: "http://homelab.danielsteman.com:8080"
        target: "_blank"
      - name: "Prometheus"
        subtitle: "Metrics"
        tag: "infra"
        url: "http://prometheus.cluster.fuck"
        target: "_blank"
      - name: "MinIO"
        subtitle: "S3-compatible storage"
        tag: "infra"
        url: "#"
        target: "_blank"
